# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Install GPG
      run: |
        echo "Install gnupg"
        sudo apt install gnupg -y
        echo "Sucess in instalation gnupg"
        
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v2
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASS }}
    
    - name: Build with Maven
      run: mvn clean deploy --file pom.xml
      env:
       GPG_PASSWORD: ${{ secrets.GPG_PASS }}
       JIRA_SONARTYPE_ID: ${{ secrets.JIRA_SONARTYPE_ID }}   
       JIRA_SONARTYPE_PWD: ${{ secrets.JIRA_SONARTYPE_PWD }}
